/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletsRouteImport } from './routes/wallets'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as MainRouteImport } from './routes/main'
import { Route as LoginRouteImport } from './routes/login'
import { Route as BudgetsRouteImport } from './routes/budgets'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MainIndexRouteImport } from './routes/main/index'
import { Route as MainWalletsIndexRouteImport } from './routes/main/wallets/index'
import { Route as MainTransactionsIndexRouteImport } from './routes/main/transactions/index'
import { Route as MainBudgetsIndexRouteImport } from './routes/main/budgets/index'
import { Route as MainWalletsCreateRouteImport } from './routes/main/wallets/create'
import { Route as MainTransactionsCreateRouteImport } from './routes/main/transactions/create'
import { Route as MainBudgetsCreateRouteImport } from './routes/main/budgets/create'

const WalletsRoute = WalletsRouteImport.update({
  id: '/wallets',
  path: '/wallets',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const MainRoute = MainRouteImport.update({
  id: '/main',
  path: '/main',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BudgetsRoute = BudgetsRouteImport.update({
  id: '/budgets',
  path: '/budgets',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MainIndexRoute = MainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainRoute,
} as any)
const MainWalletsIndexRoute = MainWalletsIndexRouteImport.update({
  id: '/wallets/',
  path: '/wallets/',
  getParentRoute: () => MainRoute,
} as any)
const MainTransactionsIndexRoute = MainTransactionsIndexRouteImport.update({
  id: '/transactions/',
  path: '/transactions/',
  getParentRoute: () => MainRoute,
} as any)
const MainBudgetsIndexRoute = MainBudgetsIndexRouteImport.update({
  id: '/budgets/',
  path: '/budgets/',
  getParentRoute: () => MainRoute,
} as any)
const MainWalletsCreateRoute = MainWalletsCreateRouteImport.update({
  id: '/wallets/create',
  path: '/wallets/create',
  getParentRoute: () => MainRoute,
} as any)
const MainTransactionsCreateRoute = MainTransactionsCreateRouteImport.update({
  id: '/transactions/create',
  path: '/transactions/create',
  getParentRoute: () => MainRoute,
} as any)
const MainBudgetsCreateRoute = MainBudgetsCreateRouteImport.update({
  id: '/budgets/create',
  path: '/budgets/create',
  getParentRoute: () => MainRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/budgets': typeof BudgetsRoute
  '/login': typeof LoginRoute
  '/main': typeof MainRouteWithChildren
  '/register': typeof RegisterRoute
  '/wallets': typeof WalletsRoute
  '/main/': typeof MainIndexRoute
  '/main/budgets/create': typeof MainBudgetsCreateRoute
  '/main/transactions/create': typeof MainTransactionsCreateRoute
  '/main/wallets/create': typeof MainWalletsCreateRoute
  '/main/budgets': typeof MainBudgetsIndexRoute
  '/main/transactions': typeof MainTransactionsIndexRoute
  '/main/wallets': typeof MainWalletsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/budgets': typeof BudgetsRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/wallets': typeof WalletsRoute
  '/main': typeof MainIndexRoute
  '/main/budgets/create': typeof MainBudgetsCreateRoute
  '/main/transactions/create': typeof MainTransactionsCreateRoute
  '/main/wallets/create': typeof MainWalletsCreateRoute
  '/main/budgets': typeof MainBudgetsIndexRoute
  '/main/transactions': typeof MainTransactionsIndexRoute
  '/main/wallets': typeof MainWalletsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/budgets': typeof BudgetsRoute
  '/login': typeof LoginRoute
  '/main': typeof MainRouteWithChildren
  '/register': typeof RegisterRoute
  '/wallets': typeof WalletsRoute
  '/main/': typeof MainIndexRoute
  '/main/budgets/create': typeof MainBudgetsCreateRoute
  '/main/transactions/create': typeof MainTransactionsCreateRoute
  '/main/wallets/create': typeof MainWalletsCreateRoute
  '/main/budgets/': typeof MainBudgetsIndexRoute
  '/main/transactions/': typeof MainTransactionsIndexRoute
  '/main/wallets/': typeof MainWalletsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/budgets'
    | '/login'
    | '/main'
    | '/register'
    | '/wallets'
    | '/main/'
    | '/main/budgets/create'
    | '/main/transactions/create'
    | '/main/wallets/create'
    | '/main/budgets'
    | '/main/transactions'
    | '/main/wallets'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/budgets'
    | '/login'
    | '/register'
    | '/wallets'
    | '/main'
    | '/main/budgets/create'
    | '/main/transactions/create'
    | '/main/wallets/create'
    | '/main/budgets'
    | '/main/transactions'
    | '/main/wallets'
  id:
    | '__root__'
    | '/'
    | '/budgets'
    | '/login'
    | '/main'
    | '/register'
    | '/wallets'
    | '/main/'
    | '/main/budgets/create'
    | '/main/transactions/create'
    | '/main/wallets/create'
    | '/main/budgets/'
    | '/main/transactions/'
    | '/main/wallets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BudgetsRoute: typeof BudgetsRoute
  LoginRoute: typeof LoginRoute
  MainRoute: typeof MainRouteWithChildren
  RegisterRoute: typeof RegisterRoute
  WalletsRoute: typeof WalletsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallets': {
      id: '/wallets'
      path: '/wallets'
      fullPath: '/wallets'
      preLoaderRoute: typeof WalletsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/main': {
      id: '/main'
      path: '/main'
      fullPath: '/main'
      preLoaderRoute: typeof MainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/budgets': {
      id: '/budgets'
      path: '/budgets'
      fullPath: '/budgets'
      preLoaderRoute: typeof BudgetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/main/': {
      id: '/main/'
      path: '/'
      fullPath: '/main/'
      preLoaderRoute: typeof MainIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/main/wallets/': {
      id: '/main/wallets/'
      path: '/wallets'
      fullPath: '/main/wallets'
      preLoaderRoute: typeof MainWalletsIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/main/transactions/': {
      id: '/main/transactions/'
      path: '/transactions'
      fullPath: '/main/transactions'
      preLoaderRoute: typeof MainTransactionsIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/main/budgets/': {
      id: '/main/budgets/'
      path: '/budgets'
      fullPath: '/main/budgets'
      preLoaderRoute: typeof MainBudgetsIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/main/wallets/create': {
      id: '/main/wallets/create'
      path: '/wallets/create'
      fullPath: '/main/wallets/create'
      preLoaderRoute: typeof MainWalletsCreateRouteImport
      parentRoute: typeof MainRoute
    }
    '/main/transactions/create': {
      id: '/main/transactions/create'
      path: '/transactions/create'
      fullPath: '/main/transactions/create'
      preLoaderRoute: typeof MainTransactionsCreateRouteImport
      parentRoute: typeof MainRoute
    }
    '/main/budgets/create': {
      id: '/main/budgets/create'
      path: '/budgets/create'
      fullPath: '/main/budgets/create'
      preLoaderRoute: typeof MainBudgetsCreateRouteImport
      parentRoute: typeof MainRoute
    }
  }
}

interface MainRouteChildren {
  MainIndexRoute: typeof MainIndexRoute
  MainBudgetsCreateRoute: typeof MainBudgetsCreateRoute
  MainTransactionsCreateRoute: typeof MainTransactionsCreateRoute
  MainWalletsCreateRoute: typeof MainWalletsCreateRoute
  MainBudgetsIndexRoute: typeof MainBudgetsIndexRoute
  MainTransactionsIndexRoute: typeof MainTransactionsIndexRoute
  MainWalletsIndexRoute: typeof MainWalletsIndexRoute
}

const MainRouteChildren: MainRouteChildren = {
  MainIndexRoute: MainIndexRoute,
  MainBudgetsCreateRoute: MainBudgetsCreateRoute,
  MainTransactionsCreateRoute: MainTransactionsCreateRoute,
  MainWalletsCreateRoute: MainWalletsCreateRoute,
  MainBudgetsIndexRoute: MainBudgetsIndexRoute,
  MainTransactionsIndexRoute: MainTransactionsIndexRoute,
  MainWalletsIndexRoute: MainWalletsIndexRoute,
}

const MainRouteWithChildren = MainRoute._addFileChildren(MainRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BudgetsRoute: BudgetsRoute,
  LoginRoute: LoginRoute,
  MainRoute: MainRouteWithChildren,
  RegisterRoute: RegisterRoute,
  WalletsRoute: WalletsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
